#!/usr/bin/env python
'''
Created on Feb 19, 2013

@author: fahrstuhl
'''
from diarium import write
from diarium import read
from diarium import search
from diarium import config
from diarium import sync

if __name__ == "__main__":
    import argparse
    argumentParser = argparse.ArgumentParser(description="Diarium journal")
    subparsers = argumentParser.add_subparsers(title="subcommands")

    parser_read = subparsers.add_parser('read', help='Read a page of your journal.')
    parser_read.add_argument("-d", "--date",
                            help="Date or name of page to read.")
    parser_read.set_defaults(func=read.externalRead)

    parser_write = subparsers.add_parser('write', help='Write a new journal entry')
    parser_write.add_argument("-d", "--date",
                            help="Date or name of page to edit")
    parser_write.add_argument("-t", "--tags", help="Comma separated tags of entry")
    parser_write.add_argument("-c", "--content", help="Content of entry")
    parser_write.add_argument("-q", "--quiet", action="store_true", help="Don't open editor")
    parser_write.set_defaults(func=write.externalWrite)

    parser_search = subparsers.add_parser('search', help='Search for journal entries')
    parser_search.add_argument("tags", help="Comma separated tags to look for.")
    parser_search.add_argument("-f", "--fromDate", help="Search for tags in pages from this date on.")
    parser_search.add_argument("-t", "--tilDate", help= "Search for tags in pages until this date.")
    parser_search.set_defaults(func=search.externalPrintFindings)

    parser_sync = subparsers.add_parser('sync', help='Synchronize two journals')
    sync_subparser = parser_sync.add_subparsers(title='sync-commands')
    sync_pull = sync_subparser.add_parser('pull', help='Pull pages from a remote directory to a local directory')
    sync_pull.add_argument("remote", help="Remote directory")
    sync_pull.add_argument("-l", "--local", help="Local directory", default=config.journalPath)
    sync_pull.set_defaults(func=sync.extPull)
    sync_push = sync_subparser.add_parser('push', help='Push pages from a local directory to a remote directory')
    sync_push.add_argument("remote", help="Remote directory")
    sync_push.add_argument("-l", "--local", help="Local directory", default=config.journalPath)
    sync_push.set_defaults(func=sync.extPush)
    sync_merge = sync_subparser.add_parser('merge', help='Synchronize a local and a remote directory')
    sync_merge.add_argument("remote", help="Remote directory")
    sync_merge.add_argument("-l", "--local", help="Local directory", default=config.journalPath)
    sync_merge.set_defaults(func=sync.extMerge)

    args = argumentParser.parse_args()
    args.func(args)
